[2025-02-20T10:52:31.767] [ERROR] error - Testing Error Get Kategori Error: Data Kategori Tidak Tersedia
[2025-02-20T10:52:31.767] [ERROR] error - Error: Data Kategori Tidak Tersedia
    at D:\Dev SIPPP\PMO\sidapet-be-reb\rebuild-sidapet-be\src\services\api\v1\trxPenjaringan-service.ts:81:31
    at Generator.next (<anonymous>)
    at fulfilled (D:\Dev SIPPP\PMO\sidapet-be-reb\rebuild-sidapet-be\src\services\api\v1\trxPenjaringan-service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 422,
  status: 'error'
}
[2025-02-20T10:53:49.917] [ERROR] error - Testing Error Get Kategori Error: Data Kategori Tidak Tersedia
[2025-02-20T10:53:49.918] [ERROR] error - Error: Data Kategori Tidak Tersedia
    at D:\Dev SIPPP\PMO\sidapet-be-reb\rebuild-sidapet-be\src\services\api\v1\trxPenjaringan-service.ts:84:23
    at Generator.next (<anonymous>)
    at fulfilled (D:\Dev SIPPP\PMO\sidapet-be-reb\rebuild-sidapet-be\src\services\api\v1\trxPenjaringan-service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 422,
  status: 'error'
}
[2025-02-20T10:54:46.557] [ERROR] error - Testing Error Get Kategori Error: Data Kategori Tidak Tersedia
[2025-02-20T10:54:46.558] [ERROR] error - Error: Data Kategori Tidak Tersedia
    at D:\Dev SIPPP\PMO\sidapet-be-reb\rebuild-sidapet-be\src\services\api\v1\trxPenjaringan-service.ts:87:23
    at Generator.next (<anonymous>)
    at fulfilled (D:\Dev SIPPP\PMO\sidapet-be-reb\rebuild-sidapet-be\src\services\api\v1\trxPenjaringan-service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 422,
  status: 'error'
}
[2025-02-20T10:56:06.641] [ERROR] error - Testing Error Get Kategori Error: Internal server error.
[2025-02-20T10:56:06.642] [ERROR] error - Error: Internal server error.
    at D:\Dev SIPPP\PMO\sidapet-be-reb\rebuild-sidapet-be\src\services\api\v1\trxPenjaringan-service.ts:91:23
    at Generator.next (<anonymous>)
    at fulfilled (D:\Dev SIPPP\PMO\sidapet-be-reb\rebuild-sidapet-be\src\services\api\v1\trxPenjaringan-service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 500,
  status: 'error'
}
[2025-02-20T10:56:53.185] [ERROR] error - Testing Error Get Kategori Error: Internal server error.
[2025-02-20T10:56:53.185] [ERROR] error - Error: Internal server error.
    at D:\Dev SIPPP\PMO\sidapet-be-reb\rebuild-sidapet-be\src\services\api\v1\trxPenjaringan-service.ts:90:23
    at Generator.next (<anonymous>)
    at fulfilled (D:\Dev SIPPP\PMO\sidapet-be-reb\rebuild-sidapet-be\src\services\api\v1\trxPenjaringan-service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 500,
  status: 'error'
}
[2025-02-20T10:57:54.696] [ERROR] error - Testing Error Get Kategori Error: Internal server error.
[2025-02-20T10:57:54.696] [ERROR] error - Error: Internal server error.
    at D:\Dev SIPPP\PMO\sidapet-be-reb\rebuild-sidapet-be\src\services\api\v1\trxPenjaringan-service.ts:90:23
    at Generator.next (<anonymous>)
    at fulfilled (D:\Dev SIPPP\PMO\sidapet-be-reb\rebuild-sidapet-be\src\services\api\v1\trxPenjaringan-service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 500,
  status: 'error'
}
[2025-02-20T11:00:08.239] [ERROR] error - Testing Error Get Kategori Error: harap isi daftar undangan
[2025-02-20T11:00:08.242] [ERROR] error - Error: harap isi daftar undangan
    at D:\Dev SIPPP\PMO\sidapet-be-reb\rebuild-sidapet-be\src\services\api\v1\trxPenjaringan-service.ts:86:23
    at Generator.next (<anonymous>)
    at fulfilled (D:\Dev SIPPP\PMO\sidapet-be-reb\rebuild-sidapet-be\src\services\api\v1\trxPenjaringan-service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 422,
  status: 'error'
}
[2025-02-20T11:26:13.589] [ERROR] error - Testing Error Get Kategori Error: harap isi daftar undangan
[2025-02-20T11:26:13.590] [ERROR] error - Error: harap isi daftar undangan
    at D:\Dev SIPPP\PMO\sidapet-be-reb\rebuild-sidapet-be\src\services\api\v1\trxPenjaringan-service.ts:87:23
    at Generator.next (<anonymous>)
    at fulfilled (D:\Dev SIPPP\PMO\sidapet-be-reb\rebuild-sidapet-be\src\services\api\v1\trxPenjaringan-service.ts:28:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 422,
  status: 'error'
}
[2025-02-20T11:28:56.195] [ERROR] error - Testing Error Get Kategori Error: harap isi daftar undangan
[2025-02-20T11:28:56.198] [ERROR] error - Error: harap isi daftar undangan
    at D:\Dev SIPPP\PMO\sidapet-be-reb\rebuild-sidapet-be\src\services\api\v1\trxPenjaringan-service.ts:87:23
    at Generator.next (<anonymous>)
    at fulfilled (D:\Dev SIPPP\PMO\sidapet-be-reb\rebuild-sidapet-be\src\services\api\v1\trxPenjaringan-service.ts:28:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 422,
  status: 'error'
}
[2025-02-18T16:45:54.842] [ERROR] error - Error: getaddrinfo ENOTFOUND dinovalley.ut.ac.id
    at C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\src\middleware\authorization.ts:117:13
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\src\middleware\authorization.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 401,
  status: 'error'
}
[2025-02-18T16:46:25.702] [ERROR] error - Error: getaddrinfo ENOTFOUND dinovalley.ut.ac.id
    at C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\src\middleware\authorization.ts:117:13
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\src\middleware\authorization.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 401,
  status: 'error'
}
[2025-02-18T16:46:47.822] [ERROR] error - Error [SequelizeConnectionError]: database � db_sidapet � tidak ada
    at Client._connectionCallback (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\sequelize\src\dialects\postgres\connection-manager.js:191:24)
    at Client._handleErrorWhileConnecting (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\pg\lib\client.js:326:19)
    at Client._handleErrorMessage (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\pg\lib\client.js:346:19)
    at Connection.emit (node:events:519:28)
    at Connection.emit (node:domain:488:12)
    at C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\pg\lib\connection.js:116:12
    at Parser.parse (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\pg-protocol\src\parser.ts:103:9)
    at Socket.<anonymous> (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12) {
  parent: error: database � db_sidapet � tidak ada
      at Parser.parseErrorMessage (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\pg-protocol\src\parser.ts:368:69)
      at Parser.handlePacket (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\pg-protocol\src\parser.ts:187:21)
      at Parser.parse (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\pg-protocol\src\parser.ts:102:30)
      at Socket.<anonymous> (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\pg-protocol\src\index.ts:7:48)
      at Socket.emit (node:events:519:28)
      at Socket.emit (node:domain:488:12)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Socket.Readable.push (node:internal/streams/readable:390:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
    length: 93,
    severity: 'FATAL',
    code: '3D000',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'postinit.c',
    line: '1021',
    routine: 'InitPostgres'
  },
  original: error: database � db_sidapet � tidak ada
      at Parser.parseErrorMessage (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\pg-protocol\src\parser.ts:368:69)
      at Parser.handlePacket (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\pg-protocol\src\parser.ts:187:21)
      at Parser.parse (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\pg-protocol\src\parser.ts:102:30)
      at Socket.<anonymous> (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\pg-protocol\src\index.ts:7:48)
      at Socket.emit (node:events:519:28)
      at Socket.emit (node:domain:488:12)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Socket.Readable.push (node:internal/streams/readable:390:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
    length: 93,
    severity: 'FATAL',
    code: '3D000',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'postinit.c',
    line: '1021',
    routine: 'InitPostgres'
  }
}
[2025-02-18T16:46:54.246] [ERROR] error - Error [SequelizeConnectionError]: database � db_sidapet � tidak ada
    at Client._connectionCallback (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\sequelize\src\dialects\postgres\connection-manager.js:191:24)
    at Client._handleErrorWhileConnecting (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\pg\lib\client.js:326:19)
    at Client._handleErrorMessage (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\pg\lib\client.js:346:19)
    at Connection.emit (node:events:519:28)
    at Connection.emit (node:domain:488:12)
    at C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\pg\lib\connection.js:116:12
    at Parser.parse (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\pg-protocol\src\parser.ts:103:9)
    at Socket.<anonymous> (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12) {
  parent: error: database � db_sidapet � tidak ada
      at Parser.parseErrorMessage (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\pg-protocol\src\parser.ts:368:69)
      at Parser.handlePacket (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\pg-protocol\src\parser.ts:187:21)
      at Parser.parse (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\pg-protocol\src\parser.ts:102:30)
      at Socket.<anonymous> (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\pg-protocol\src\index.ts:7:48)
      at Socket.emit (node:events:519:28)
      at Socket.emit (node:domain:488:12)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Socket.Readable.push (node:internal/streams/readable:390:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
    length: 93,
    severity: 'FATAL',
    code: '3D000',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'postinit.c',
    line: '1021',
    routine: 'InitPostgres'
  },
  original: error: database � db_sidapet � tidak ada
      at Parser.parseErrorMessage (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\pg-protocol\src\parser.ts:368:69)
      at Parser.handlePacket (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\pg-protocol\src\parser.ts:187:21)
      at Parser.parse (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\pg-protocol\src\parser.ts:102:30)
      at Socket.<anonymous> (C:\Users\irgyr\Documents\kerjaan\promise\rebuild-si-dapet-be\node_modules\pg-protocol\src\index.ts:7:48)
      at Socket.emit (node:events:519:28)
      at Socket.emit (node:domain:488:12)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Socket.Readable.push (node:internal/streams/readable:390:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
    length: 93,
    severity: 'FATAL',
    code: '3D000',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'postinit.c',
    line: '1021',
    routine: 'InitPostgres'
  }
}
[2025-02-20T12:36:23.308] [ERROR] error - Error: Token Not Match
    at D:\Dev SIPPP\PMO\sidapet-be-reb\rebuild-sidapet-be\src\middleware\authorization.ts:108:13
    at Generator.next (<anonymous>)
    at fulfilled (D:\Dev SIPPP\PMO\sidapet-be-reb\rebuild-sidapet-be\src\middleware\authorization.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 401,
  status: 'error'
}
[2025-02-20T12:36:30.572] [ERROR] error - Testing Error Get Kategori Error: Transaction cannot be rolled back because it has been finished with state: rollback
[2025-02-20T12:36:30.572] [ERROR] error - Error: Transaction cannot be rolled back because it has been finished with state: rollback
    at Transaction.rollback (D:\Dev SIPPP\PMO\sidapet-be-reb\rebuild-sidapet-be\node_modules\sequelize\src\transaction.js:82:13)
    at D:\Dev SIPPP\PMO\sidapet-be-reb\rebuild-sidapet-be\src\services\api\v1\trxPenjaringan-service.ts:110:17
    at Generator.next (<anonymous>)
    at fulfilled (D:\Dev SIPPP\PMO\sidapet-be-reb\rebuild-sidapet-be\src\services\api\v1\trxPenjaringan-service.ts:28:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[2025-02-20T12:37:05.621] [ERROR] error - Testing Error Get Kategori Error: Email Tidak Valid
[2025-02-20T12:37:05.622] [ERROR] error - Error: Email Tidak Valid
    at D:\Dev SIPPP\PMO\sidapet-be-reb\rebuild-sidapet-be\src\services\api\v1\trxPenjaringan-service.ts:111:23
    at Generator.next (<anonymous>)
    at fulfilled (D:\Dev SIPPP\PMO\sidapet-be-reb\rebuild-sidapet-be\src\services\api\v1\trxPenjaringan-service.ts:28:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 422,
  status: 'error'
}
